version: '3.7'

services:
  app:
    container_name: app
    env_file:
      - .env
    build:
      context: .
      target: development
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules:delegated
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn dev
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - 5432:5432
